#! /bin/sh

# Copyright 2018 Israel Flores. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#
# Author:     Israel Flores (https://github.com/idflores)
# File:       clean
# Purpose:    cleans up NPM's global scope after executing `./run`

npm uninstall -g truffle
npm uninstall -g webpack
